-- pg_lexo upgrade from 0.5.0 to 0.6.0
-- 
-- This migration removes the lexo schema and moves all objects to the default schema.
-- Type renamed: lexo.lexorank -> lexo
-- Functions renamed: lexo.X() -> lexo_X()
--
-- IMPORTANT: This is a breaking change. After running this migration:
-- 1. Tables with lexo.lexorank columns need to be altered
-- 2. All function calls need to be updated
--
-- Note: The actual type and function definitions are auto-generated by pgrx
-- during the extension upgrade process.

-- Drop old schema-based objects if they exist
DO $$
BEGIN
    -- Drop old functions from lexo schema
    DROP FUNCTION IF EXISTS lexo.first() CASCADE;
    DROP FUNCTION IF EXISTS lexo.after(lexo.lexorank) CASCADE;
    DROP FUNCTION IF EXISTS lexo.before(lexo.lexorank) CASCADE;
    DROP FUNCTION IF EXISTS lexo.between(lexo.lexorank, lexo.lexorank) CASCADE;
    DROP FUNCTION IF EXISTS lexo.next(text, text, text, text) CASCADE;
    DROP FUNCTION IF EXISTS lexo.add_lexo_column_to(text, text) CASCADE;
    DROP FUNCTION IF EXISTS lexo.rebalance(text, text, text, text) CASCADE;
    DROP FUNCTION IF EXISTS lexo.after_text(text) CASCADE;
    DROP FUNCTION IF EXISTS lexo.before_text(text) CASCADE;
    DROP FUNCTION IF EXISTS lexo.first_text() CASCADE;
    DROP FUNCTION IF EXISTS lexo.between_text(text, text) CASCADE;
    
    -- Drop old type from lexo schema
    DROP TYPE IF EXISTS lexo.lexorank CASCADE;
    
    -- Drop lexo schema if empty
    DROP SCHEMA IF EXISTS lexo CASCADE;
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Error during cleanup: %', SQLERRM;
END $$;
